version: '3.7'

services:
  web:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "7069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_modules:/mnt/extra-addons
    environment:
      - ODOO_LIST_DB=false
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "7000:5432"